// Automatically generated by zod_gen
import * as z from 'zod';

export const GetHistoryResponseSchema = z.object({
  notes: z.string().nullable(),
  mood: z.string().nullable(),
  date: z.string(),
  spotify_details: z.object({
  id: z.string(),
  name: z.string(),
  album: z.object({
  images: z.array(z.object({
  url: z.string(),
  height: z.number().nullable(),
  width: z.number().nullable()
}))
}),
  external_urls: z.object({
  spotify: z.string()
}),
  artists: z.array(z.object({
  name: z.string()
}))
}).nullable()
});
export type GetHistoryResponse = z.infer<typeof GetHistoryResponseSchema>;

export const TrackSchema = z.object({
  id: z.string(),
  album: z.object({
  images: z.array(z.object({
  url: z.string(),
  height: z.number().nullable(),
  width: z.number().nullable()
}))
}),
  artists: z.array(z.object({
  name: z.string()
})),
  name: z.string(),
  uri: z.string()
});
export type Track = z.infer<typeof TrackSchema>;

export const TracksPageSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  album: z.object({
  images: z.array(z.object({
  url: z.string(),
  height: z.number().nullable(),
  width: z.number().nullable()
}))
}),
  artists: z.array(z.object({
  name: z.string()
})),
  name: z.string(),
  uri: z.string()
})),
  total: z.number(),
  limit: z.number(),
  offset: z.number(),
  href: z.string(),
  next: z.string().nullable(),
  previous: z.string().nullable()
});
export type TracksPage = z.infer<typeof TracksPageSchema>;

export const UserResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  avatar_url: z.string().nullable(),
  daily_song_playlist_id: z.string().nullable()
});
export type UserResponse = z.infer<typeof UserResponseSchema>;

