// Automatically generated by zod_gen
import * as z from 'zod';

export const TrackSchema = z.object({
  id: z.string(),
  album: z.object({
  images: z.array(z.object({
  url: z.string(),
  height: z.number().nullable(),
  width: z.number().nullable()
}))
}),
  artists: z.array(z.object({
  name: z.string()
})),
  name: z.string(),
  uri: z.string()
});
export type Track = z.infer<typeof TrackSchema>;

export const TracksPageSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  album: z.object({
  images: z.array(z.object({
  url: z.string(),
  height: z.number().nullable(),
  width: z.number().nullable()
}))
}),
  artists: z.array(z.object({
  name: z.string()
})),
  name: z.string(),
  uri: z.string()
})),
  total: z.number(),
  limit: z.number(),
  offset: z.number(),
  href: z.string(),
  next: z.string().nullable(),
  previous: z.string().nullable()
});
export type TracksPage = z.infer<typeof TracksPageSchema>;

