// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { Artist } from "./Artist";

export type Track = { album: Album, artists: Array<Artist>, name: string, uri: string, };
