// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

export type TracksPage = { items: Array<Track>, total: number, limit: number, offset: number, href: string, next: string | null, previous: string | null, };
