// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = { id: string, name: string, email: string, avatar_url: string | null, daily_song_playlist_id: string | null, };
